# File              : action.yaml
# Author            : Alexandre Saison <alexandre.saison@inarix.com>
# Date              : 18.03.2021
# Last Modified Date : 19.05.2021
# Last Modified By   : Alexandre Saison <alexandre.saison@inarix.com>
name: 'Bookish-Happiness'
description: 'Push Nutshell to ArgoCD in PullRequest'
outputs:
  modelInstanceId: # id of output
    description: 'Register model instance id.'
runs:
  using: 'docker'
  image: 'Dockerfile'